mp=input("Enter the number of matches palyed")
runs=input("Enter  the runs scored by the player")
balls=input("Enter the number of balls the batsman has played")
mp=int(mp)
runs=int(runs)
balls=int(balls)
average=(runs/mp)
sr=((runs/balls)*100)
average=int(average)
sr=int(sr)
print('AVERAGE RUN',average)
print('Strike Rate=',sr)
